language: objective-c
osx_image: xcode11.3
xcode_sdk: iphonesimulator13.2
install:
- gem install xcpretty
- carthage bootstrap --platform iOS
script:
  - set -o pipefail
  - travis_retry xcodebuild -project KRTournamentView.xcodeproj -scheme KRTournamentView -destination "platform=iOS Simulator,name=iPhone 11" build-for-testing test | xcpretty
notifications:
  email: false
