platform :ios, '11.0'

target 'KRTournamentViewDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'KRTournamentView', path: '../KRTournamentView.podspec'

end
